MeepProductsMvc/Models/ListarProdutosOmie.cs
using Newtonsoft.Json;
using System.Text.Json.Serialization;

namespace MeepProductsMvc.Models
{
    public class ListarProdutosOmie
    {
        [JsonProperty(PropertyName = "pagina")]
        public string? Pagina { get; set; }

        [JsonProperty(PropertyName = "registros_por_pagina")]
        public string? Registros_por_pagina { get; set; }

        [JsonProperty(PropertyName = "filtrar_apenas_omiepdv")]
        public string? Filtrar_apenas_omiepdv { get; set; }
    }

    public class Authorization
    {
        [JsonPropertyName("call")]
        public string? Call { get; set; } 

        [JsonPropertyName("app_key")]
        public string? App_key { get; set; }

        [JsonPropertyName("app_secret")]
        public string? App_secret { get; set; }

        [JsonPropertyName("param")]
        public ListarProdutosOmie? Param { get; set; }
    }
    public class ListarResponse
    {

        [JsonPropertyName("pagina")]
        public int? Pagina { get; set; }

        [JsonPropertyName("total_de_paginas")]
        public int? Total_de_paginas { get; set; }

        [JsonPropertyName("registros")]
        public int? Registros { get; set; }

        [JsonPropertyName("total_de_registros")]
        public int? Total_de_registros { get; set; }

        [JsonPropertyName("produto_servico_resumido")]
        public List<ResponseContent>? Produto_servico_resumido { get; set; }
    }

    public class ResponseContent
    {
        [JsonPropertyName("codigo")]
        public string? Codigo { get; set; }

        [JsonPropertyName("codigo_produto")]
        public string? Codigo_produto { get; set; }

        [JsonPropertyName("codigo_produto_integracao")]
        public string? Codigo_produto_integracao { get; set; }

        [JsonPropertyName("descricao")]
        public string? Descricao { get; set; }

        [JsonPropertyName("valor_unitario")]
        public decimal? Valor_unitario { get; set; }
    }
}
 

MeepProductsMvc/Models/ProdutoOmie.cs
using System.Text.Json.Serialization;

namespace MeepProductsMvc.Models
{
    public class ProdutoOmie
    {
        [JsonPropertyName("call")]
        public string? Call { get; set; }

        [JsonPropertyName("app_key")]
        public string? AppKey { get; set; }

        [JsonPropertyName("app_secret")]
        public string? AppSecret { get; set; }

        [JsonPropertyName("param")]
        public Param[]? Param { get; set; }
        
    }

    public class Param
    {
        [JsonPropertyName("codigo_produto_integracao")]
        public string? CodigoProdutoIntegracao { get; set; }

        [JsonPropertyName("codigo")]
        public string? Codigo { get; set; }

        [JsonPropertyName("descricao")]
        public string? Descricao { get; set; }

        [JsonPropertyName("unidade")]
        public string? Unidade { get; set; }

        [JsonPropertyName("ncm")]
        public string? Ncm { get; set; }
    }
}

MeepProductsMvc/Models/ProdutoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MeepProductsMvc.Models
{
    public class ProdutoViewModel
    {
        public int Id { get; set; }
        public int CategoriaId { get; set; }
        [Required(ErrorMessage = "O nome do produto é obrigatório")]
        public string? Nome { get; set; }
        public string? Descricao { get; set; }
        public decimal? Preco { get; set; }
        public int? Ncm { get; set; }
        public DateTime DataCriacao { get; set; }
    }
}

MeepProductsMvc/Models/ProdutosOmieTeste.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Text.Json.Serialization;

namespace MeepProductsMvc.Models
{
    public class ParamObject
    {
        [JsonProperty(PropertyName = "codigo_produto_integracao")]
        public string? Codigo_produto_integracao { get; set; }

        [JsonProperty(PropertyName = "codigo")]
        public string? Codigo { get; set; }

        [JsonProperty(PropertyName = "descricao")]
        public string? Descricao { get; set; }

        [JsonProperty(PropertyName = "unidade")]
        public string? Unidade { get; set; }

        [JsonProperty(PropertyName = "ncm")]
        public string? Ncm { get; set; }

        [JsonProperty(PropertyName = "valor_unitario")]
        public string? Valor_unitario { get; set; }
    }
    public class ProdutosOmieTeste
    {
        [JsonPropertyName("call")]
        public string? Call { get; set; }

        [JsonPropertyName("app_key")]
        public string? App_key { get; set; }

        [JsonPropertyName("app_secret")]
        public string? App_secret { get; set; }

        [JsonPropertyName("param")]
        public ParamObject? Param { get; set; }
    }
}

MeepProductsMvc/Controllers/HomeController.cs
using MeepProductsMvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeepProductsMvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MeepProductsMvc/Controllers/ProdutosController.cs
using MeepProductsMvc.Exceptions;
using MeepProductsMvc.Interfaces;
using MeepProductsMvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeepProductsMvc.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly IProdutoService _produtoService;

        public ProdutosController(IProdutoService produtoService)
        {
            _produtoService = produtoService;
        }
        /*
                [HttpGet]
                public async Task<ActionResult<IEnumerable<ProdutosOmieTeste>>> Index()
                {
                    var result = await _produtoService.GetProdutos();

                    if (result is null)
                    {
                        return View("Error");
                    }
                    return View(result);
                }

        */
        [HttpGet]
        public async Task<ActionResult<IEnumerable<ListarProdutosOmie>>> Index()
        {
            var result = await _produtoService.ListarProdutos();
            //var responseContent = result.Produto_servico_resumido[0];

            if (result is null)
            {
                return View("Error");
            }
           return View(result.Produto_servico_resumido);
        }

        [HttpGet("CriarProduto")]
          public IActionResult CriarProduto() 
          { 
              return View();
          }

        [HttpPost("CriarProduto")]
        public async Task<ActionResult<ProdutosOmieTeste>> CriarProduto(ProdutosOmieTeste produtosOmieTeste)
        {
            if (ModelState.IsValid)
            {
                var result = await _produtoService.PostOmieTeste(produtosOmieTeste);

                if (result == null )
                    return RedirectToAction(nameof(Index));
            }
            ViewBag.Erro = "Erro ao criar o produto";
            return View();
        }
    }
}

MeepProductsMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo</h1>
    <h3>Consumindo api MeepProducts</h3>
    <img src="~/imagens/logo (2).png" asp-append-version="true" />
</div>

MeepProductsMvc/Views/Produtos/CriarProduto.cshtml
@model MeepProductsMvc.Models.ProdutosOmieTeste

<h2>Criar um Produto</h2>

<form asp-action="CriarProduto">
    <div class="form-horizontal">
        <hr />
        
        @* <div class="form-group">
            <label asp-for="Call" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Call" class="form-control" />
                <span asp-validation-for="Call" class="text-danger"></span>
            </div>
        <div class="form-group">
                <label asp-for="App_key" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                    <input asp-for="App_key" class="form-control" />
                    <span asp-validation-for="App_key" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
                <label asp-for="App_secret" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                    <input asp-for="App_secret" class="form-control" />
                    <span asp-validation-for="App_secret" class="text-danger"></span>
            </div>
        </div>
        *@
        <div class="form-group">
                <label asp-for="Param.Codigo_produto_integracao" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                    <input asp-for="Param.Codigo_produto_integracao" class="form-control" />
                    <span asp-validation-for="Param.Codigo_produto_integracao" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Param.Codigo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                    <input asp-for="Param.Codigo" class="form-control" />
                    <span asp-validation-for="Param.Codigo" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Param.Descricao" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                    <input asp-for="Param.Descricao" class="form-control" />
                    <span asp-validation-for="Param.Descricao" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Param.Unidade" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                    <input asp-for="Param.Unidade" class="form-control" />
                    <span asp-validation-for="Param.Unidade" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Param.Ncm" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                    <input asp-for="Param.Ncm" class="form-control" />
                    <span asp-validation-for="Param.Ncm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Param.Valor_unitario" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Param.Valor_unitario" class="form-control" />
                    <span asp-validation-for="Param.Valor_unitario" class="text-danger"></span>
                </div>
        </div>
        
        <div class="form-group" style="padding-top: 10px">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-success" />
                Retornar
            </div>
        </div>
    </div>
    
    @if (@ViewBag.Erro != null)
    {
        <div style="color:red">
            <h4>@ViewBag.Erro</h4>
        </div>
    }
</form>

MeepProductsMvc/Views/Produtos/Index.cshtml
@model IEnumerable<MeepProductsMvc.Models.ResponseContent>

<h2>Produtos</h2>
<hr />

<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
              
                <a asp-action="CriarProduto" class="btn btn-primary">
                    <span title="enviar Omie" class="fas fa-plus"></span> Novo Produto
                </a>

            </div>
        </div>
    </div>
</div>
<br />
<div class="panel panel-default">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Codigo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Codigo_produto)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descricao)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Valor_unitario)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Codigo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Codigo_produto)
                    <td>
                        @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td>
                            @Html.DisplayFor(modelItem => item.Valor_unitario)
                    </td>
                    </td>
                   
                <td>
                <a asp-action="AtualizarProduto" asp-route-id="@item.Codigo_produto_integracao" title="Editar" class="btn btn-warning">
                <span class="fas fa-edit"></span>
                </a>
                <a asp-action="DeletarProduto" asp-route-id="@item.Codigo_produto_integracao" title="Deletar" class="btn btn-danger">
                <span class="fas fa-trash-alt"></span>
                </a>
                </td>          
                </tr>
            }
        </tbody>
    </table>
</div>

MeepProductsMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MeepProductsMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MeepProductsMvc.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" 
    integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MeepProductsMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CriarProduto" asp-action="Index">EnviarOmie</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MeepProductsMvc - <a asp-area="" src="https://github.com/Raullsouza">https://github.com/Raullsouza</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>